version: '3.8'
services:
    db:
        image: postgres
        environment:
            POSTGRES_DB: chatdb
            POSTGRES_USER: chatuser
            POSTGRES_PASSWORD: chatpassword
        volumes:
            - db_data:/var/lib/postgresql/data

    app:
        build: .
        ports:
            - '9000:9000'
        depends_on:
            - db
        environment:
            DATABASE_HOST: db
            DATABASE_PORT: 5432
            DATABASE_USER: chatuser
            DATABASE_PASSWORD: chatpassword
            DATABASE_DB: chatdb
        command: ['npm', 'run', 'start']

volumes:
    db_data:
